ecommerce/ecommerce/cart/urls.py
from django.urls import path

from cart import views

app_name='cart'
urlpatterns = [
path('add/<int:product_id>/',views.add_cart,name='add_cart'),
path('',views.cart_detail,name='cart_detail'),
path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')

]

ecommerce/ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
app_name='shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL
                          ,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path('',views.searchresult,name='searchresult')
]

ecommerce/ecommerce/shop/urls.py
from django.urls import path

from shop import views
app_name='shop'
urlpatterns = [
path('',views.allproduct,name= 'allproduct'),
 path('<slug:c_slug>/',views.allproduct,name = 'product_by_cat'),
 path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='procatdetail')

]

ecommerce/ecommerce/cart/models.py
from django.db import models
from shop .models import product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format( self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return  self.product.price * self.quantity
    def __str__(self):
        return '{}'.format( self.product)

ecommerce/ecommerce/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/ecommerce/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:product_by_cat',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)
class product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:procatdetail', args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
            return '{}'.format(self.name)

ecommerce/ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import  product
from .models import  Cart,CartItem
from django.core.exceptions import  ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return  cart
def add_cart(request,product_id):
    products=product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=products,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=products,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item=CartItem.objects.get(product=products,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=products, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce/ecommerce/search_app/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q
# Create your views here.
def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

ecommerce/ecommerce/shop/views.py
from django.http import HttpResponse, request
from django.shortcuts import render,get_object_or_404



# Create your views here.
from .models import category, product
from django.core.paginator import Paginator,EmptyPage,InvalidPage



def allproduct(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)

        products_list = product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return  render(request,"category.html",{'category':c_page,'products': products })

def proDetail(request,c_slug,product_slug):
    try:
        products=product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'products':products})

ecommerce/ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
     <meta name="description" content="{% block metadescription %}{% endblock %}">


    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-image:url(/static/img/about.jpg">
<div class="container">

{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecommerce/ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
THIS IS CART PAGE..PLEASE REVIEW YOUR ITEMS
{% endblock %}
{% block title %}
    CART-EASY BUY
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
             <h1 class="text-centermy_title">
                       Your cart is Empty
             </h1>
        <br>
                   <p class="text-center">
                      Click <a href="{% url 'shop:allproduct' %}"> Here </a>to continue shopping
                    </p>
    </div>
</div>
{% else %}
<div>
     <div class="text-center">
             <br>
                     <h1 class="text-center my_title">
            Your cart
        </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
               <tr>
                     <th colspan="5" style="background-color:green;">
                         Your Items
                     </th>
               </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
             <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}"  style="width:100px; height:100px;" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: Rs {{cart_item.product.price }}
                    <br>
                    Qty : {{cart_item.quantity}} x  {{cart_item}}
                </td>
                <td>
                Rs {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}

                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus-circle custom_icon"></i></a><br>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a><br>
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                   <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash-circle custom_icon"></i></a>
                   </td>
                 {% endif %}
             </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thread">
            <tr>
                <th>
                    CheckOut
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your cart items before proceeding with payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total amount :<strong>Rs {{total}}</strong>

                </td>
            </tr>
            </tbody>

        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allproduct' %}" class="btn btn-success btn-block my_custom_button">Continue Shopping</a>
            <a href="" class="btn btn-primary btn-block my_custom_button">Pay Now </a>
        </div>
    </div>
</div>
</div>
    {% endif %}
{% endblock %}

ecommerce/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
     {{category.description|truncatewords:155}}
    {% else %}
      welcome to the world of online shopping
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
     {{category.name}}-ONLINE Stores
    {% else %}
      welcome to the world of online shopping
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a href="{% url 'shop:allproduct' %}">Our products</a> </p>
    </div>
    </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" >
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <!--<p class="text-justify">{{category.description}}</p>-->
</div>
{% else %}
<div>
    <!--<img class="my_image my_image_padding" src="{% static 'img/about.jpg' %}" alt="our products" width="100%" height="300px">-->
</div>
<br>
<div>
    <h1 class="text-center my_title"> our product collections</h1>
    <p class="text-justify">ONLINE SHOPPING
</p>
</div>
 {% endif %}
<div class="container">
    <div class="row mx_auto">
        {%  for product in products.object_list  %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text-center" style="min-width:15rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="80px" height="70px" ></a><br>
            <div class="card-body">
                <h4> {{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
        </div>
        </div>
    {% endfor %}

</div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-danger  {% if products.number == pg %} active {% endif %}">{{pg}}</a>
       {% endfor %}<hr>
    </div>
         {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce/ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom  my_footer">
    <p class="text-center">&copy; ONLINE  Stores pvt Lmtd.All rights reserved</p>
</div>

ecommerce/ecommerce/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-warning"   >
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allproduct' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#80ff00;">
            <li><a class="dropdown-item" href="{% url 'shop:allproduct' %}">All products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
       </ul>
      <form class="d-flex" action="{%url 'search_app:searchresult' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q"aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     {{product.description|truncatewords:155}}



{% endblock %}
{% block title %}
    {% if category %}
     {{product.name}}-ONLINE Stores

    {% endif %}
{% endblock %}
{% block content %}


<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allproduct' %}">Home</a>     <a href ="{{products.category.get_url}}">{{products.category}}</a>    {{products.name}}</p>
    </div>
<div class="container">
    <br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem" >
            <img src="{{products.image.url}}" alt ="{{products.name}}" width="300px" height="300px">
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h1 class="my_prod_title"><strong>{{products.name}}</strong></h1>
            <p>{{products.price}}</p>
            <p class="my_title"><b>Product Description</b></p>
            <p class="text-justify my_prod_text">{{products.description}}</p><br>
            {% if products.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p><br>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart'  products.id %}">Add to cart</a>
            {% endif %}
        </div>
    </div>
</div>
</div>

{% endblock %}

ecommerce/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

  we have now MI  brands only available,coming soon other brands
{% endblock %}
{% block title %}
     search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"><b>You are searched for :"{{query}}"</b></p>
</div>
<div class="container">
<div class="row mx_auto">
        {%  for product in products %}

        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a><br>
        </div>
        </div>

            <div class="card-body">
                <h4> {{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>



        </div>
    {% empty %}
    <div class="row mx_auto">
        <p class="text-center my_search_text"><b>0 results found</b></p>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}